
drop table locacao;
drop table pedido;
drop table cliente;
drop table fita;
drop table filme;

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER (10) NOT NULL,
    CPF VARCHAR2 (11) NOT NULL,
    NOME VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE CLIENTE ADD CONSTRAINT CLI_PK PRIMARY KEY ( ID_CLIENTE ) ;
ALTER TABLE CLIENTE ADD CONSTRAINT CLI_UK_CPF UNIQUE ( CPF );
CREATE SEQUENCE CLIENTE_SEQ;

CREATE TABLE FILME (
    ID_FILME NUMBER (10) NOT NULL,
    TITULO VARCHAR2 (30) NOT NULL,
    CATEGORIA_FILME VARCHAR2 (7) NOT NULL
  ) ;
ALTER TABLE FILME ADD CONSTRAINT FIL_PK PRIMARY KEY ( ID_FILME ) ;
ALTER TABLE FILME ADD CONSTRAINT FIL_UK_TITULO UNIQUE ( TITULO );
CREATE SEQUENCE FILME_SEQ;

CREATE TABLE FITA (
    ID_FITA NUMBER (10) NOT NULL,
    TITULO VARCHAR2 (30) NOT NULL,
    SITUACAO_FITA VARCHAR2 (10) NOT NULL,
    ID_FILME NUMBER (10) NOT NULL
);
ALTER TABLE FITA ADD CONSTRAINT FIT_PK PRIMARY KEY ( ID_FITA ) ;
ALTER TABLE FITA ADD CONSTRAINT FIL_FIT_FK FOREIGN KEY ( ID_FILME ) REFERENCES FILME (ID_FILME) ;
CREATE SEQUENCE FITA_SEQ;

CREATE TABLE PEDIDO (
    ID_PEDIDO NUMBER (10) NOT NULL,
    SITUACAO_PEDIDO VARCHAR2 (9) NOT NULL,
    ID_CLIENTE NUMBER (10) NOT NULL,
    VALOR_TOTAL DECIMAL (9,2) NOT NULL,
    VALOR_DIVIDA DECIMAL (9,2) NOT NULL
);
ALTER TABLE PEDIDO ADD CONSTRAINT PED_PK PRIMARY KEY ( ID_PEDIDO ) ;
ALTER TABLE PEDIDO ADD CONSTRAINT CLI_PED_FK FOREIGN KEY ( ID_CLIENTE ) REFERENCES CLIENTE (ID_CLIENTE) ;
CREATE SEQUENCE PEDIDO_SEQ;

CREATE TABLE LOCACAO (
    ID_LOCACAO NUMBER (10) NOT NULL,
    ID_PEDIDO NUMBER (10) NOT NULL,
    ID_FITA NUMBER (10) NOT NULL,
    DATA_ENTREGA DATE NOT NULL,
    PRAZO_ENTREGA INT NOT NULL
);
 
ALTER TABLE LOCACAO ADD CONSTRAINT LOC_PK PRIMARY KEY ( ID_LOCACAO ) ;
ALTER TABLE LOCACAO ADD CONSTRAINT PED_LOC_FK FOREIGN KEY ( ID_PEDIDO ) REFERENCES PEDIDO (ID_PEDIDO) ;
ALTER TABLE LOCACAO ADD CONSTRAINT FIT_LOC_FK FOREIGN KEY ( ID_FITA ) REFERENCES FITA (ID_FITA) ;
CREATE SEQUENCE LOCACAO_SEQ;